contact_info:
  email: "mattias.holmgren46@gmail.com"

packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim
  - less

brew:
  taps:
    - aws/tap
    - homebrew/bundle
    - homebrew/cask
    - homebrew/core
    - candid82/brew
    - derailed/k9s
    - yqrashawn/goku
  casks:
    - 1password
    - google-chrome
    - discord
    - flux
    - karabiner-elements
    - macpass
    - medis
    - obsidian
    - raycast
    - utm
    - alacritty
    - alt-tab
    - aws-vault
    - brave-browser
    - hiddenbar
    - spotify
  packages:
    common:
      - 1password-cli
      - asdf
      - autoconf
      - automake
      - awscli
      - bat
      - codespell
      - coreutils
      - direnv
      - dust
      - fd
      - fzf
      - gh
      - ghq
      - jq
      - k9s
      - kustomize
      - lazygit
      - p7zip
      - pre-commit
      - python-yq
      - ripgrep
      - sponge
      - tealdeer
      - tre-command
      - tree
      - tree-sitter
      - zoxide
      - cmatrix
      - graphviz
      - htop
      - imagemagick
      - lsd
      - ncdu
      - redis
      - derailed/k9s/k9s
      - pngpaste
    darwin:
      - dockutil
      - switchaudio-osx
      - ffmpeg
      - gawk
      - gnu-getopt
      - gnu-sed
      - watch
      - wget
      - xz
    linux: []
  packages_from_source:
    - duf

dotfiles:
  repo: "https://github.com/mattjh1/dotfiles"
  branch: "main"

neovim:
  build_from_source: false
  directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
  build_dependencies:
    - autoconf
    - automake
    - cmake
    - curl
    - doxygen
    - g++
    - gettext
    - libtool
    - libtool-bin
    - ninja-build
    - pkg-config
    - unzip

asdf_version: "v0.9.0"
asdf_plugins:
  - name: "python"
    repository: "https://github.com/danhper/asdf-python"
    versions:
      - 3.11.0
    delete_versions: []
    global: system

  - name: "golang"
    repository: "https://github.com/kennyp/asdf-golang"
    versions:
      - 1.22.0
    delete_versions: []
    global: system

  - name: "ruby"
    repository: "https://github.com/asdf-vm/asdf-ruby"
    versions:
      - 3.3.0
    delete_versions: []
    global: system

  - name: "nodejs"
    repository: "https://github.com/asdf-vm/asdf-nodejs"
    versions:
      - 20.11.1
    delete_versions: []
    global: system

  - name: "kubectl"
    repository: "https://github.com/asdf-community/asdf-kubectl"
    versions:
      - 1.23.0
    delete_versions: []
    global: 1.23.0

golang:
  path: "{{ ansible_user_dir }}/.go"
  packages:
    - golang.org/x/tools/gopls@latest

nodejs:
  packages:
    - yarn

vscode:
  keybindings_path: "{{ ansible_user_dir }}/Library/Application\ Support/Code/User/keybindings.json"
  settings_path: "{{ ansible_user_dir }}/Library/Application\ Support/Code/User/keybindings.json"

  extensions:
    - adamcowley.neo4j-vscode
    - alefragnani.bookmarks
    - amazonwebservices.aws-toolkit-vscode
    - angular.ng-template
    - arcticicestudio.nord-visual-studio-code
    - batisteo.vscode-django
    - bierner.markdown-emoji
    - christian-kohler.npm-intellisense
    - dbaeumer.vscode-eslint
    - donjayamanne.python-environment-manager
    - donjayamanne.python-extension-pack
    - eamodio.gitlens
    - ecmel.vscode-html-css
    - editorconfig.editorconfig
    - edonet.vscode-command-runner
    - esbenp.prettier-vscode
    - fivethree.vscode-ionic-snippets
    - formulahendry.auto-rename-tag
    - github.vscode-pull-request-github
    - golang.go
    - jakeboone02.cypher-query-language
    - jebbs.plantuml
    - johnpapa.angular-essentials
    - johnpapa.angular2
    - kevinrose.vsc-python-indent
    - mechatroner.rainbow-csv
    - mikestead.dotenv
    - ms-azuretools.vscode-docker
    - ms-python.black-formatter
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-vscode-remote.remote-containers
    - njpwerner.autodocstring
    - orsenkucher.vscode-graphql
    - pkief.material-icon-theme
    - pmneo.tsimporter
    - redhat.vscode-yaml
    - rvest.vs-code-prettier-eslint
    - shyykoserhiy.git-autoconfig
    - steoates.autoimport
    - sumneko.lua
    - syler.sass-indented
    - tomoki1207.pdf
    - visualstudioexptteam.intellicode-api-usage-examples
    - visualstudioexptteam.vscodeintellicode
    - vscodevim.vim
    - wholroyd.jinja
    - yzhang.markdown-all-in-one

dockitems_disabled:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - Terminal
  - iBooks
  - iTunes

dockitems_enabled:
  - name: Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Alacritty
    path: "/Applications/Alacritty.app"
    pos: 2
  - name: Discord
    path: "/Applications/Discord.app"
    pos: 3
  - name: Edge
    path: "/Applications/Microsoft Edge.app"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5
  - name: Obsidian
    path: "/Applications/Obsidian.app"
    pos: 6
  - name: Outlook
    path: "/Applications/Microsoft Outlook.app"
    pos: 7
  - name: Teams
    path: "/Applications/Microsoft Teams (work or school).app"
    pos: 8
