packages:
  - build-essential
  - libssl-dev
  - llvm
  - python3-pip
  - python-is-python3
  - vim
  - less

brew:
  taps:
    - aws/tap
    - homebrew/bundle
    - homebrew/cask
    - homebrew/core
    - candid82/brew
    - derailed/k9s
    - yqrashawn/goku
  casks:
    - 1password
    - google-chrome
    - discord
    - flux
    - karabiner-elements
    - macpass
    - medis
    - obsidian
    - raycast
    - utm
    - alacritty
    - alt-tab
    - aws-vault
    - brave-browser
    - hiddenbar
  packages:
    common:
      - asdf
      - autoconf
      - automake
      - awscli
      - bat
      - codespell
      - coreutils
      - direnv
      - dust
      - fd
      - fzf
      - gh
      - ghq
      - jq
      - k9s
      - kustomize
      - lazygit
      - p7zip
      - pre-commit
      - python-yq
      - ripgrep
      - sponge
      - tealdeer
      - tre-command
      - tree
      - tree-sitter
      - zoxide
      - cmatrix
      - graphviz
      - htop
      - imagemagick
      - lsd
      - ncdu
      - redis
      - derailed/k9s/k9s
      - pngpaste
    darwin:
      - dockutil
      - switchaudio-osx
      - ffmpeg
      - gawk
      - gnu-getopt
      - gnu-sed
      - watch
      - wget
      - xz
    linux: []
  packages_from_source:
    - duf

dotfiles:
  repo: "https://github.com/mattjh1/dotfiles"
  branch: "main"

neovim:
  build_from_source: false
  directory: "{{ ansible_user_dir }}/Development/repository/github.com/neovim/neovim"
  build_dependencies:
    - autoconf
    - automake
    - cmake
    - curl
    - doxygen
    - g++
    - gettext
    - libtool
    - libtool-bin
    - ninja-build
    - pkg-config
    - unzip

asdf_version: "v0.9.0"
asdf_plugins:
  - name: "python"
    repository: "https://github.com/danhper/asdf-python"
    versions:
      - 3.12
    delete_versions: []
    global: system

  - name: "golang"
    repository: "https://github.com/kennyp/asdf-golang"
    versions:
      - 1.22.0
    delete_versions: []
    global: system

  - name: "ruby"
    repository: "https://github.com/asdf-vm/asdf-ruby"
    versions:
      - 3.3.0
    delete_versions: []
    global: system

  - name: "nodejs"
    repository: "https://github.com/asdf-vm/asdf-nodejs"
    versions:
      - 20.11.1
    delete_versions: []
    global: system

  - name: "kubectl"
    repository: "https://github.com/asdf-community/asdf-kubectl"
    versions:
      - 1.23.0
    delete_versions: []
    global: 1.23.0

golang:
  path: "{{ ansible_user_dir }}/.go"
  packages:
    - golang.org/x/tools/gopls@latest

nodejs:
  packages:
    - yarn

dockitems_disabled:
  - App Store
  - Contacts
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Notes
  - Photos
  - Reminders
  - Safari
  - Terminal
  - iBooks
  - iTunes

dockitems_enabled:
  - name: Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Alacritty
    path: "/Applications/Alacritty.app"
    pos: 2
  - name: Discord
    path: "/Applications/Discord.app"
    pos: 3
  - name: Edge
    path: "/Applications/Microsoft Edge.app/"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5
  - name: Obsidian
    path: "/Applications/Obsidian.app"
    pos: 6
  - name: Outlook
    path: "/Applications/Microsoft Outlook.app"
    pos: 7
  - name: Teams
    path: "/Applications/Microsoft Teams (work or school).app"
    pos: 8
