---
- hosts: 127.0.0.1
  gather_facts: yes
  strategy: linear
  connection: local

  vars_files:
    - config.yaml

  roles:
    - name: common
      tags: common

    - name: fonts
      tags: fonts

    - name: dotfiles
      tags: dotfiles

    - name: neovim
      tags: neovim

    - name: asdf
      tags: asdf

    - name: 1password
      tags: 1password

    - name: go
      tags: go

    - name: docker
      tags: docker

    - name: tmux
      tags: tmux

    - name: hammerspoon
      tags: hammerspoon

    - name: system_defaults
      tags: system_defaults

    - name: zsh
      tags: zsh

    - name: podman
      tags: podman
