---
- import_tasks: darwin.yaml
  when: ansible_os_family == "Darwin"

- import_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- import_tasks: rhel.yaml
  when: ansible_os_family == "RedHat"
