---
- import_tasks: darwin.yaml
  when: ansible_facts['os_family'] == "Darwin"

- import_tasks: ubuntu.yaml
  when: ansible_facts['os_family'] == "Debian"

- import_tasks: rhel.yaml
  when: ansible_facts['os_family'] == "RedHat"
