---
- import_tasks: darwin.yaml
  when: ansible_os_family == "Darwin"

- import_tasks: ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- import_tasks: rhel.yaml
  when: ansible_distribution == "RedHat"
