---
- block:
    - include_tasks: set_osx_defaults.yaml
      loop: "{{ osx_global_defaults }}"
  tags:
    - defaults
    - global

- block:
    - include_tasks: set_osx_defaults.yaml
      loop: "{{ osx_alt_tab_defaults }}"
  tags:
    - defaults
    - alt-tab

- import_tasks: dock.yaml
  tags: dock
